services:
  db:
    image: postgres:14
    restart: unless-stopped
    networks:
      - internal
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./db:/var/lib/postgresql/data:rw

  bot:
    image: ghcr.io/bsmg/yatb
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - internal
    env_file:
      - .env

  site:
    image: ghcr.io/bsmg/yatb-site
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./sitedb:/app/db:rw

networks:
  internal: